<?php
/** @var \Coveo\Search\Block\Tracking\Checkout $block */
$isLibraryIncluded = $block->isLibraryIncluded();
$trackingProductsParams = $block->getProductsTrackingParams();
$trackingOrderParams = $block->getOrderTrackingParams();
?>

<?php if ($isLibraryIncluded === true): ?>

    <script id="<?=$block->getScriptId()?>" type='text/javascript'>
        require(['coveouascriptv2'], function(){
          var uid='<?=$trackingProductsParams[0]['uid'];?>';
          window.initCoveo(function() {
        <?php foreach($trackingProductsParams as $productData): ?>
        coveoua('ec:addProduct', <?=json_encode($productData);?>);
        <?php endforeach ?>
        coveoua('ec:setAction', 'purchase', <?=json_encode($trackingOrderParams);?>);
          });
        });
    </script>

<?php else: ?>

    <script id="<?=$block->getScriptId()?>" type='text/javascript'>
        window.CoveoTrackingData = {
            "products": <?=json_encode($trackingProductParams);?>,
            "checkout": <?=json_encode($trackingOrderParams);?>,
            "action": 'purchase',
        };
    </script>

<?php endif ?>
