<?php
/** @var \Coveo\Search\Block\Tracking\LibraryInit $block */
$debugMode = $block->isDebugMode();
$trackingKey = $block->getKey();
$cookieDomain = $block->getCookieDomain('auto');
$currency = $block->getCurrencyCode();
$uid = $block->getCustomerId();
$storeid = $block->getStoreCode();
$siteid = $block->getLanguage();
$searchid = $block->getSearchId();
$api = $block->getApi();
?>

<script id="<?=$block->getScriptId()?>" type="text/javascript">
  var coveoinit=false;

  function getCookie(name) {
    const value = `; ${document.cookie}`;
    const parts = value.split(`; ${name}=`);
    if (parts.length === 2) return parts.pop().split(';').shift();
  }

  window.initCoveo=function(callback){
    //Take uid from Cookie
    mycustId = getCookie('coveo_UID');
    if (mycustId==undefined) {
      mycustId = 'anonymous';
    }
    if (coveoinit) {
      if (mycustId!='') {
        coveoua('set','userId',mycustId);
      }

      
      callback();
      return;
    }
    require(['coveouascriptv2'], function(){
    coveoinit=true;
    
    coveoua("init", "<?=$trackingKey?>","<?=$api?>");
    if (mycustId!='') {
        coveoua('set','userId',mycustId);
      }

      coveoua('set', 'custom',  {
        context_store_id: '<?=$storeid?>',
        context_website: '<?=$siteid?>'
      });

<?php if($currency): ?>
coveoua('set','currencyCode','<?=$currency?>');
<?php endif; ?>
<?php if($searchid!='' && $searchid!=null): ?>
coveoua('set','searchId','<?=$searchid?>');
<?php endif; ?>
<?php if($debugMode): ?>
coveoua('set','debug','true');
<?php endif; ?>
callback();
});
}

</script>
