<?php
/** @var \Coveo\Search\Block\Tracking\ProductView $block */
$isLibraryIncluded = $block->isLibraryIncluded();
$trackingParameters = $block->getProductTrackingParams();
?>

<?php if ($isLibraryIncluded === true): ?>

<script id="<?=$block->getScriptId()?>" type="text/javascript">
    initCoveo();
    coveoua('ec:addProduct', <?=json_encode($trackingParameters);?>);
    coveoua('ec:setAction', 'detail');
</script>

<?php else: ?>

<script id="<?=$block->getScriptId()?>" type="text/javascript">
    window.CoveoTrackingData = {
        product: <?=json_encode($trackingParameters);?>,
        action: 'detail'
    };
</script>

<?php endif ?>
